# Generated by Django 4.2.4 on 2023-08-24 20:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gestantes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.IntegerField(default=2, verbose_name='Tipo archivo')),
                ('tipdoc', models.CharField(blank=True, choices=[('CC', 'CEDULA DE CIUDA'), ('CE', 'CEDULA DE EXTR.'), ('MS', 'MENOR SIN IDENT'), ('NU', 'N.UNICO IDENT'), ('PA', 'PASAPORTE'), ('RC', 'REGISTRO CIVIL'), ('TI', 'TARJETA IDENT.'), ('PE', 'PERMISO PERMANE'), ('CN', 'NACIDO VIVO'), ('SC', 'SALVO CONDUTO'), ('AS', 'ADULTO SIN IDEN'), ('PT', 'PER PROTEC TEMP')], max_length=2, null=True, verbose_name='Tipo de documento')),
                ('nro_doc', models.CharField(db_index=True, max_length=25, verbose_name='Documento de identificación')),
                ('fecha_parto', models.DateField(verbose_name='Fecha de parto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nro_doc'],
            },
        ),
        migrations.CreateModel(
            name='SoporteGestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('IC', 'Inicio de control'), ('VH', 'VIH'), ('SF', 'Sifilis'), ('HC', 'Historia clinica')], max_length=2, verbose_name='Tipo archivo')),
                ('soporte', models.FileField(upload_to=gestantes.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Soporte')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('datosgestante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestantes.datosgestante')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoGestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.IntegerField(default=2, verbose_name='Tipo archivo')),
                ('tipo_caso', models.CharField(choices=[('1', 'Mayor de 95 años'), ('2', 'Alteraciones nutricionales'), ('3', 'Consulta a servicios de urgencias'), ('4', 'Hospitalización'), ('5', 'Laboratorios alterados'), ('6', 'Antecendes de preeclampsia'), ('7', 'Riesgo de preeclampsia'), ('8', 'Menos de cuatro controles prenatales mediando la semana gestacional 30'), ('9', 'Morbilidad materna externa'), ('10', 'Riesgo de tromboembolismo'), ('10', 'Diagnóstico de enfermedad del colágeno'), ('10', 'Diagnóstico de algún tipo de cáncer')], max_length=2, verbose_name='Tipo caso')),
                ('fecha_seguimiento', models.DateField(verbose_name='Fecha de seguimiento')),
                ('tipo_seguimiento', models.CharField(choices=[('1', 'Contacto telefónico'), ('2', 'Visita domiciliaria'), ('3', 'Visita de auditor concurrente en hospitalización'), ('4', 'Otro')], max_length=2, verbose_name='Tipo de seguimiento')),
                ('asig_cita_pm', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=2, verbose_name='Asignación cita profesional medicina')),
                ('asig_cita_me', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=2, verbose_name='Asignación cita medicina especializada')),
                ('referencia_inst', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=2, verbose_name='Referencia mayor complejidad')),
                ('can_entrega_med', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=2, verbose_name='Canalización entrega de medicamentos')),
                ('entrega_med', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=2, verbose_name='Entrega de medicamentos')),
                ('info_ciudado_sal', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=2, verbose_name='Información cuidado salud')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('datosgestante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestantes.datosgestante')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadGestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.IntegerField(default=2, verbose_name='Tipo archivo')),
                ('fecha_parto', models.DateField(verbose_name='Fecha de parto')),
                ('cod_cups', models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='codigo cups')),
                ('finalidad', models.CharField(blank=True, max_length=2, null=True, verbose_name='Finalidad tecnologia salud')),
                ('clas_ries_ges', models.CharField(choices=[('4', 'Alto riesgo'), ('5', 'Bajo riesgo'), ('21', 'Riesgo no evaluado')], max_length=2, verbose_name='Clasificación riesgo gestacional')),
                ('clas_ries_precl', models.CharField(choices=[('4', 'Alto riesgo'), ('5', 'Bajo riesgo'), ('21', 'Riesgo no evaluado')], max_length=2, verbose_name='Clasificación riesgo preclampsia')),
                ('suministro_asa', models.CharField(choices=[('0', 'No aplica'), ('1', 'Si se suministra'), ('21', 'Riesgo no evaluado')], max_length=2, verbose_name='Suministro asa')),
                ('suministro_acido', models.CharField(choices=[('0', 'No aplica'), ('1', 'Si se suministra'), ('21', 'Riesgo no evaluado')], max_length=2, verbose_name='Suministro acido folico')),
                ('suministro_sulfato', models.CharField(choices=[('0', 'No aplica'), ('1', 'Si se suministra'), ('21', 'Riesgo no evaluado')], max_length=2, verbose_name='Suministro sulfato ferroso')),
                ('suministro_calcio', models.CharField(choices=[('0', 'No aplica'), ('1', 'Si se suministra'), ('21', 'Riesgo no evaluado')], max_length=2, verbose_name='Suministro calcio ')),
                ('fecha_suministro', models.DateField(verbose_name='Fecha suministro')),
                ('suministro_antic', models.CharField(choices=[('0', 'No aplica'), ('1', 'Dispositivo intrauterino'), ('2', 'Dispositivo intrauterino y preservativo'), ('3', 'implante sudérmico'), ('4', 'implante sudérmico y preservativo '), ('5', 'Oral'), ('6', 'Oral y preservativo'), ('7', 'Inyectable mensual'), ('8', 'Inyectable mensual y preservativo'), ('9', 'Inyectable trimestral'), ('10', 'Inyectable trimestral y preservativo'), ('13', 'Esterilización'), ('14', 'Esterilización y preservativo'), ('15', 'Preservativo')], max_length=2, verbose_name='Suministro anticonceptivo ')),
                ('fecha_salida', models.DateField(verbose_name='Fecha salida atención parto cesarea')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('datosgestante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestantes.datosgestante')),
            ],
            options={
                'ordering': ['cod_cups'],
            },
        ),
    ]
