# Generated by Django 4.2.4 on 2023-08-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0002_alter_soportegestante_datosgestante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportegestante',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to='archivos_soportes/', verbose_name='Soporte'),
        ),
    ]
