# Generated by Django 4.2.4 on 2023-08-28 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gestantes.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0003_alter_soportegestante_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportegestante',
            name='datosgestante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestantes.datosgestante'),
        ),
        migrations.AlterField(
            model_name='soportegestante',
            name='soporte',
            field=models.FileField(default=1, upload_to=gestantes.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Soporte'),
            preserve_default=False,
        ),
    ]
