# Generated by Django 4.2.4 on 2023-08-28 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0004_alter_soportegestante_datosgestante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportegestante',
            name='soporte',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Soporte'),
        ),
    ]
