# Generated by Django 4.2.4 on 2023-08-28 15:49

import django.core.validators
from django.db import migrations, models
import gestantes.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0005_alter_soportegestante_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportegestante',
            name='soporte',
            field=models.FileField(upload_to=gestantes.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Soporte'),
        ),
    ]
