# Generated by Django 4.2.4 on 2023-08-28 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0006_alter_soportegestante_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportegestante',
            name='soporte',
            field=models.FileField(upload_to='archivos_soportes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Soporte'),
        ),
        migrations.AlterField(
            model_name='soportegestante',
            name='tipo_archivo',
            field=models.CharField(choices=[('1', 'Inicio de control'), ('2', 'VIH'), ('3', 'Sifilis'), ('4', 'Historia clinica')], max_length=2, verbose_name='Tipo archivo'),
        ),
    ]
