# Generated by Django 4.2.4 on 2023-09-01 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0010_alter_soportegestante_tipo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soportegestante',
            name='soporte',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Soporte'),
        ),
    ]
