# Generated by Django 4.2.4 on 2023-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0015_alter_datosgestante_tipdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgestante',
            name='tipdoc',
            field=models.CharField(blank=True, choices=[('CC', 'CEDULA DE CIUDA'), ('CE', 'CEDULA DE EXTR.'), ('MS', 'MENOR SIN IDENT'), ('NU', 'N.UNICO IDENT'), ('PA', 'PASAPORTE'), ('RC', 'REGISTRO CIVIL'), ('TI', 'TARJETA IDENT.'), ('PE', 'PERMISO PERMANE'), ('CN', 'NACIDO VIVO'), ('SC', 'SALVO CONDUTO'), ('AS', 'ADULTO SIN IDEN'), ('PT', 'PER PROTEC TEMP')], max_length=2, null=True, verbose_name='Tipo de documento'),
        ),
    ]
