# Generated by Django 4.2.4 on 2023-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0016_alter_datosgestante_tipdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgestante',
            name='tipdoc',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo de documento'),
        ),
    ]
