# Generated by Django 4.2.4 on 2023-10-09 15:07

from django.db import migrations, models
import gestantes.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0017_alter_datosgestante_tipdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargueMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_excel', models.CharField(max_length=255, verbose_name='Nombre del archivo Excel')),
                ('soporte_excel', models.FileField(upload_to='uploads/', validators=[gestantes.models.validate_excel_file_extension], verbose_name='Soporte Excel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
