# Generated by Django 4.2.4 on 2023-10-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0018_carguemensual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carguemensual',
            name='nombre_excel',
        ),
    ]
