# Generated by Django 4.2.4 on 2023-11-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0021_informacionmensual_informaciongestante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionmensual',
            name='var282',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha_Resultado_TSH_Dos1'),
        ),
    ]
