# Generated by Django 4.2.4 on 2023-11-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0022_alter_informacionmensual_var282'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionmensual',
            name='var342',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha_Acompañamiento_Sabedor_Ancestral1'),
        ),
    ]
